# Generated by Django 5.0.6 on 2024-05-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qrcode_img',
            field=models.ImageField(blank=True, upload_to='qrcode-img/'),
        ),
    ]
